name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt install -y clang-format clang-tidy clang-tools
          sudo apt install -y build-essential g++-15 libgl1-mesa-dev libx11-dev zlib1g-dev
          sudo apt install -y libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-15 15
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-15 15

      - name: Check format and tidy
        run: mkdir build && cd build && cmake .. && cd .. && make format
        working-directory: ${{ github.workspace }}

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt install -y build-essential g++-15 libgl1-mesa-dev libx11-dev zlib1g-dev
          sudo apt install -y libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-15 15
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-15 15          

      - name: Build with make
        run: make release
        working-directory: ${{ github.workspace }}

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build with make
        run: make release
        working-directory: ${{ github.workspace }}
